### ISSUE TITLE
Respect Linebreaks or allow HTML in comment box

### ISSUE THREAD

**Issue by silvanheller** [dbisUnibas/ReqMan#1]
Either respect the formatting (linebreaks) or allow html so we can have pretty feedback formatting

**Comment by sauterl** [comment]
There is almost no restriction in what you use within the comments.
The comments are plain text and you can use whatever language you prefer to write those comments.

Depending on the export template / export target language you can format your comments as you wish.

If you would like to have a more sophisticated comment-UI, you can open another feature-request / wishlist issue.
