### ISSUE TITLE
[Visual Bug] 'Showing n items' from filter is wrong

### ISSUE THREAD

**Issue by silvanheller** [dbisUnibas/ReqMan#18]
If you filter your view and select a milestone, you're not actually showing n matche (s), but only those from the current milestone which is less.
You could now argue that this is a feature since the milestone-filter is applied afterwards...

**Comment by sauterl** [comment]
Fixed with v2.0.0-PR16 (ff5cc9c52140c02d33830cee2a11e6fc7e7e5c34)
