### ISSUE TITLE
[Minor Inconvenience] Filter does not persist when switching Milestones

### ISSUE THREAD

**Issue by silvanheller** [dbisUnibas/ReqMan#19]
Reproduce: 
* Select a Milestone
* Apply a filter
* Select another Milestone 
* Now you have to press 'filter' again

**Comment by s3inlc** [comment]
The filter also does not persist when switching between groups.

**Comment by sauterl** [comment]
Fixed with v2.0.0-PR16 (ff5cc9c52140c02d33830cee2a11e6fc7e7e5c34)
