### ISSUE TITLE
Meta Data cannot be changed

### ISSUE THREAD

**Issue by lucaro** [dbisUnibas/ReqMan#8]
Changes to the meta data of a requirement are not saved.

**Comment by sauterl** [comment]
Did you press enter before saving? If not, then:
This is default JavaFX behaviour; To commit changes made in a text field, one has to hit the enter key.

I will see what I can do about it.


## Workaround:

(For now, be sure to 
1. edit appropriate meta data field (key or value)
2. hit enter
3. save the requirement

to modify a requirement's meta data)
